project_id = "lkjgwzmolatkjupapepm"

[functions.form-submit]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.lead-distributor]
verify_jwt = false

[functions.lead-automation-runner]
verify_jwt = false

[functions.og-property]
verify_jwt = false
