project_id = "lkjgwzmolatkjupapepm"

[functions.secure-storage]
verify_jwt = false

[functions.form-submit]
verify_jwt = false

[functions.manage-roles]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

